spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Credit
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
