databaseChangeLog:
  - changeSet:
      id: 2
      author: postgres
      changes:
        - createTable:
            tableName: loan_applications
            columns:
              - column:
                  name: id
                  type: UUID
                  constraints:
                    primaryKey: true
              - column:
                  name: user_id
                  type: UUID
                  constraints:
                    nullable: false
              - column:
                  name: amount
                  type: DECIMAL(15,2)
              - column:
                  name: term_months
                  type: INT
              - column:
                  name: status
                  type: VARCHAR(50)
              - column:
                  name: created_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
        - addForeignKeyConstraint:
            constraintName: fk_loan_applications_user
            baseTableName: loan_applications
            baseColumnNames: user_id
            referencedTableName: users
            referencedColumnNames: id
            onDelete: CASCADE
